name: API Services CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/ExternalOrderApi/**'
      - 'src/InternalSystemApi/**'
      - 'src/shared/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ExternalOrderApi/**'
      - 'src/InternalSystemApi/**'
      - 'src/shared/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/
    
    - name: Build
      run: dotnet build src/ --no-restore --configuration Release
    
    - name: Run tests
      run: dotnet test tests/ --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests

  build-docker-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        service: [ExternalOrderApi, InternalSystemApi]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/bidone/${{ matrix.service }}:${{ github.sha }} \
                     -t ${{ secrets.ACR_LOGIN_SERVER }}/bidone/${{ matrix.service }}:latest \
                     -f src/${{ matrix.service }}/Dockerfile .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/bidone/${{ matrix.service }}:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/bidone/${{ matrix.service }}:latest

  deploy-to-azure:
    needs: build-docker-images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: ${{ secrets.ACR_NAME }}
        containerAppName: bidone-integration-demo
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/bidone/externalorderapi:${{ github.sha }}