name: Azure Functions CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/OrderIntegrationFunction/**'
      - 'src/shared/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/OrderIntegrationFunction/**'
      - 'src/shared/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/OrderIntegrationFunction/
    
    - name: Build
      run: dotnet build src/OrderIntegrationFunction/ --no-restore --configuration Release
    
    - name: Run tests
      run: dotnet test tests/OrderIntegrationFunction.Tests/ --no-build --configuration Release --verbosity normal

  deploy-function:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build and publish
      run: |
        dotnet restore src/OrderIntegrationFunction/
        dotnet build src/OrderIntegrationFunction/ --configuration Release
        dotnet publish src/OrderIntegrationFunction/ --configuration Release --output ./output
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}